fix std::system_error when tcp interface loses connection
  When the tcp connection is lost (remote TCP server stopped), an 'End of file' error is caught
  by the io_thread in the do_recv() that calls the close() function.

  In the close() function, we stop the io_service and wait for the end of the io_thread which
  causes an std::system_error exception (cause: Resource deadlock avoided).

  Error:   mavconn: tcp0: receive: End of file at line 250 in libmavconn/src/tcp.cpp
           terminate called after throwing an instance of 'std::system_error'
           what():  Resource deadlock avoided
           Aborted (core dumped)

  fix:
    - close() function: stop io_service if current thread id != io_thread id
    - ~MAVConnTCPClient(): stop io_service and io_thread if thread is running